customCommands:
  - key: 'm'
    description: "Commit with AI generated commit message"
    context: 'global'
    command: 'git commit -m {{.Form.AiCommitMessage}}'
    loadingText: "Generating commit message..."
    prompts:
      - type: 'input'
        title: 'Commit message'
        key: 'AiCommitMessage'
        suggestions:
          command: "ai_commit_message -n 3"